version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
    groups:
      package-patches:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
      package-security:
        applies-to: "security-updates"
        patterns:
          - "*"
